server:
  port: 7073
  servlet:
    context-path: /eport-api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/eport?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B7
        username: root
        password: admin123
                        
mybatis:
    typeAliasesPackage: vn.com.irtech.eport.**.domain
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    
jwt:
   token-expiration-time: 3600 #1 hour
   token-issuer: EPORT
   token-signing-key: Dpm4BwgXO6ad085xgVj6ysFHSTOUozr

logging:
  level:
    vn.com.irtech.eport: debug
    org.springframework: warn