eport:
  name: DNG ePort
  version: 4.2.0
  copyrightYear: 2020
  demoEnabled: true
  profile: /home/eport/uat/api/upload
  addressEnabled: true
  cacheExpireTime: 3600

server:
  port: 7073
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
#    datasource:
#        # driverClassName: com.mysql.cj.jdbc.Driver
#        # url: jdbc:mysql://localhost:3306/eport?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B7
#        # username: root
#        # password:
#        driverClassName: oracle.jdbc.OracleDriver 
#        url: jdbc:oracle:thin:@192.168.0.29:1521/EPORT
#        username: EPORT_TEST
#        password: WINNER
    profiles:
        active: test
    redis:
        enabled: true
        database: 0
        password: 
        host: 127.0.0.1
        port: 6379
        lettuce:
            pool:
                max-active: 100
                max-idle: 100
                min-idle: 50
                max-wait: 6000
        timeout: 60000

mybatis:
    typeAliasesPackage: vn.com.irtech.eport.**.domain
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml
    
jwt:
   token-expiration-time: 12000 #1 hour
   token-issuer: EPORT
   token-signing-key: Dpm4BwgXO6ad085xgVj6ysFHSTOUozr

logging:
  level:
    vn.com.irtech.eport: debug
    org.springframework: warn
    
mqtt:
  username: admin             
  password: public            
  host-url: tcp://127.0.0.1:1883                # The address and port of your own server need to be changed
