import Colors from "./Colors";
import { screen } from '@/utils';
import { sizeWidth, sizeHeight } from '@/commons';

export default {
    item: {
        position: 'relative',
        paddingVertical: 10,
        paddingRight: 5,
        width: '90%',
    },
    flexRow: {
        flexDirection: 'row',
        alignItems: 'center'
    },
    listItem: {
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#AABBCC',
        width: screen.widthsc * 0.85,
        left: 10
    },
    iconItem: {
        position: 'relative',
        paddingVertical: 10,
        paddingRight: 5,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#fff',
        borderTopColor: '#ccc',
        paddingLeft: 10,
        width: '100%',
        // height:screen.heightsc*0.28,
        zIndex: 1,
        marginBottom: 8,
        backgroundColor: '#fff',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,

        elevation: 3,
    },
    btn_top: {
        width: 40,
        height: 40,
        position: 'absolute',
        right: 5,
        justifyContent: 'flex-start',
        alignItems: 'flex-end',
    },
    btn_bottom: {
        width: 40,
        height: 40,
        position: 'absolute',
        bottom: 10,
        top: 0,
        right: -20,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 20,
        backgroundColor: '#fff',
        shadowColor: Colors.mainColor,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,

        elevation: 8,
    },
    actionButtonIcon: {
        color: 'white',
    },
    component: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 10,
    },
    row: {
        flexDirection: 'row',
    },
    formGroupL: {
        position: 'relative',
        flex: 1,
        right: 2
    },
    formGroupR: {
        position: 'relative',
        flex: 1,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.white,
    },
    containerClass: {
        flex: 1,
        backgroundColor: Colors.white,
    },
    text: {
    },
    formInfomation: {
        backgroundColor: "#E6E8FF",
        width: screen.widthsc * 0.95,
        // height: screen.widthsc * 0.2,
        borderRadius: 5,
        marginVertical: 2,
        padding: 5,
        justifyContent: 'center',
    },
    imageBackground: {
        position: 'absolute',
        width: screen.widthsc,
        height: screen.heightsc,
    },
    textDancingScript: {
        fontFamily: 'DancingScript-Bold',
    },
    textSariaSemiCondensed: {
        fontFamily: 'SairaSemiCondensed-Bold',
    },
    footer: {
        bottom: 10,
        left: 0,
        right: 0,
        alignItems: 'center',
        position: 'absolute',
    },
    textfooter: {
        fontFamily: 'SairaSemiCondensed-Bold',
    },
    flashMessageStyle: {
        fontFamily: 'SairaSemiCondensed-Bold',
    },
    mt5: { marginTop: 5 },
    mt6: { marginTop: 6 },
    mt7: { marginTop: 7 },
    mt8: { marginTop: 8 },
    mt9: { marginTop: 9 },
    mt10: { marginTop: 10 },
    mt12: { marginTop: 12 },
    mt15: { marginTop: 15 },
    mt17: { marginTop: 17 },
    mt20: { marginTop: 20 },
    mt25: { marginTop: 25 },
    mt30: { marginTop: 30 },

    mr5: { marginRight: 5 },
    mr6: { marginRight: 6 },
    mr7: { marginRight: 7 },
    mr8: { marginRight: 8 },
    mr9: { marginRight: 9 },
    mr10: { marginRight: 10 },
    mr12: { marginRight: 12 },
    mr15: { marginRight: 15 },
    mr17: { marginRight: 17 },
    mr20: { marginRight: 20 },
    mr25: { marginRight: 25 },
    mr30: { marginRight: 30 },

    ml5: { marginLeft: 5 },
    ml6: { marginLeft: 6 },
    ml7: { marginLeft: 7 },
    ml8: { marginLeft: 8 },
    ml9: { marginLeft: 9 },
    ml10: { marginLeft: 10 },
    ml12: { marginLeft: 12 },
    ml15: { marginLeft: 15 },
    ml17: { marginLeft: 17 },
    ml20: { marginLeft: 20 },
    ml25: { marginLeft: 25 },
    ml30: { marginLeft: 30 },

    mbt5: { marginBottom: 5 },
    mbt6: { marginBottom: 6 },
    mbt7: { marginBottom: 7 },
    mbt8: { marginBottom: 8 },
    mbt9: { marginBottom: 9 },
    mbt10: { marginBottom: 10 },
    mbt12: { marginBottom: 12 },
    mbt15: { marginBottom: 15 },
    mbt17: { marginBottom: 17 },
    mbt20: { marginBottom: 20 },
    mbt25: { marginBottom: 25 },
    mbt30: { marginBottom: 30 },

    pt5: { paddingTop: 5 },
    pt6: { paddingTop: 6 },
    pt7: { paddingTop: 7 },
    pt8: { paddingTop: 8 },
    pt9: { paddingTop: 9 },
    pt10: { paddingTop: 10 },
    pt12: { paddingTop: 12 },
    pt15: { paddingTop: 15 },
    pt17: { paddingTop: 17 },
    pt20: { paddingTop: 20 },
    pt25: { paddingTop: 25 },
    pt30: { paddingTop: 30 },

    pr5: { paddingRight: 5 },
    pr6: { paddingRight: 6 },
    pr7: { paddingRight: 7 },
    pr8: { paddingRight: 8 },
    pr9: { paddingRight: 9 },
    pr10: { paddingRight: 10 },
    pr12: { paddingRight: 12 },
    pr15: { paddingRight: 15 },
    pr17: { paddingRight: 17 },
    pr20: { paddingRight: 20 },
    pr25: { paddingRight: 25 },
    pr30: { paddingRight: 30 },

    pl5: { paddingLeft: 5 },
    pl6: { paddingLeft: 6 },
    pl7: { paddingLeft: 7 },
    pl8: { paddingLeft: 8 },
    pl9: { paddingLeft: 9 },
    pl10: { paddingLeft: 10 },
    pl12: { paddingLeft: 12 },
    pl15: { paddingLeft: 15 },
    pl17: { paddingLeft: 17 },
    pl20: { paddingLeft: 20 },
    pl25: { paddingLeft: 25 },
    pl30: { paddingLeft: 30 },

    pbt5: { paddingBottom: 5 },
    pbt6: { paddingBottom: 6 },
    pbt7: { paddingBottom: 7 },
    pbt8: { paddingBottom: 8 },
    pbt9: { paddingBottom: 9 },
    pbt10: { paddingBottom: 10 },
    pbt12: { paddingBottom: 12 },
    pbt15: { paddingBottom: 15 },
    pbt17: { paddingBottom: 17 },
    pbt20: { paddingBottom: 20 },
    pbt25: { paddingBottom: 25 },
    pbt30: { paddingBottom: 30 },

    f1: { flex: 1 },
    f2: { flex: 2 },
    f3: { flex: 3 },
    f4: { flex: 4 },
    f5: { flex: 5 },
    f6: { flex: 6 },
    f7: { flex: 7 },
};