spring:
  redis:
    database: 0
    password: secret
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
        max-wait: 6000
    timeout: 60000