eport:
  name: DNG ePort
  version: 4.2.0
  copyrightYear: 2020
  demoEnabled: true
  profile: D:/eport/upload
  addressEnabled: true
  cacheExpireTime: 3600

server:
  port: 7071
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    vn.com.irtech.eport: debug
    org.springframework: warn

user:
  password:
    maxRetryCount: 5

spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
  messages:
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+7
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    database: 0
    password: 
    host: 192.168.1.65
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 50
        max-wait: 6000
    timeout: 60000

mybatis:
    typeAliasesPackage: vn.com.irtech.eport.**.domain
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    configLocation: classpath:mybatis/mybatis-config.xml

pagehelper: 
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

shiro:
  user:
    loginUrl: /login
    unauthorizedUrl: /unauth
    indexUrl: /index
    captchaEnabled: false
    captchaType: math
  cookie:
    domain: 
    path: /admin
    httpOnly: true
    maxAge: 30
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    expireTime: 30
    dbSyncPeriod: 1
    validationInterval: 10
    maxSession: -1
    kickoutAfter: false

xss: 
  enabled: true
  excludes: /system/notice/*
  urlPatterns: /system/*,/monitor/*,/tool/*

mqtt:
  username: admin
  password: public 
  host-url: tcp://113.176.195.221:1883    
  #host-url: tcp://localhost:1883               # The address and port of your own server need to be changed 

websocket:
   endpoint: /eport_admin
   app-destination-prefix: /eport_admin
   message-broker: /eport_admin

