CREATE SEQUENCE SEQ_SHIPMENT_IMAGE;

CREATE TABLE SHIPMENT_IMAGE
(
    ID          NUMBER(20, 0) NOT NULL PRIMARY KEY,
    SHIPMENT_ID NUMBER(20, 0) NOT NULL,
    PATH        VARCHAR2(255) NOT NULL,
    CREATE_BY   VARCHAR2(64) DEFAULT '',
    CREATE_TIME TIMESTAMP    DEFAULT NULL,
    UPDATE_BY   VARCHAR2(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP    DEFAULT NULL
);

CREATE UNIQUE INDEX INDEX_PATH ON SHIPMENT_IMAGE (PATH);
