CREATE TABLE IF NOT EXISTS `container_info` (
  `cntr_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `cntr_no` varchar(20) COLLATE utf8_bin NOT NULL COMMENT 'Container Number',
  `sztp2` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'Size/type 2',
  `fe` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'F/E',
  `ptnr_code` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Operator ',
  `block` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'yard location ',
  `bay` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'yard location ',
  `roww` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'yard location ',
  `tier` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'yard location ',
  `wgt` int(11) DEFAULT NULL COMMENT 'Weight ',
  `vsl_nm` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Vessel name',
  `consignee` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'Shipper/consignee',
  `booking_no` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'Booking Number',
  `bl_no` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'BL number',
  `seal_no1` varchar(50) COLLATE utf8_bin DEFAULT NULL COMMENT 'Seal Number',
  `dispatch_mode` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Gate mode for terminal in',
  `dispatch_mode2` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'Gate mode for terminal out',
  `in_date` datetime DEFAULT NULL COMMENT 'Gate In Date',
  `out_date` datetime DEFAULT NULL COMMENT 'Gate Out Date',
  `vgm` varchar(20) COLLATE utf8_bin DEFAULT NULL COMMENT 'VGM',
  `cntr_state` varchar(3) COLLATE utf8_bin DEFAULT NULL COMMENT 'Container State  (S: Stacking, D:Delivered)',
  `remark` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'Remark',
  PRIMARY KEY (`cntr_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Container Infomation';
